sonar.organization=codeurjc-students
sonar.projectKey=codeurjc-students_2026-INFRACTURE

sonar.sources=backend/src/main/java,frontend/app
sonar.tests=backend/src/test/java,frontend/test

sonar.java.source=25
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
