CREATE TABLE component_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_key VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_component_template
        PRIMARY KEY (id),

    CONSTRAINT uk_component_template_key
        UNIQUE (template_key),

    CONSTRAINT uk_component_template_type
        UNIQUE (type),

    CONSTRAINT ck_component_template_type
        CHECK (
            type IN (
                'HTTP_SERVICE',
                'WORKER',
                'LOAD_GENERATOR',
                'POSTGRESQL',
                'REDIS',
                'RABBITMQ'
            )
        )
);

INSERT INTO component_template (template_key, name, type, enabled)
VALUES
    ('http-service', 'HTTP Service', 'HTTP_SERVICE', TRUE),
    ('worker', 'Worker', 'WORKER', TRUE),
    ('load-generator', 'Load Generator', 'LOAD_GENERATOR', TRUE),
    ('postgresql', 'PostgreSQL', 'POSTGRESQL', TRUE),
    ('redis', 'Redis', 'REDIS', TRUE),
    ('rabbitmq', 'RabbitMQ', 'RABBITMQ', TRUE)
ON CONFLICT (template_key) DO UPDATE
SET
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    enabled = EXCLUDED.enabled;
