spring.application.name=infracture-backend

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/infracture}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:infracture}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:infracture_dev}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
